### ISSUE TITLE
Uncaught Exception in in `modules/cors.py`

### ISSUE THREAD

**Issue by snguyenthanh** [flipkart-incubator/Astra#38] opened 2018-05-04 07:24 UTC
I got the following error when trying to submit an URL to my local REST server:
```
  File "../astra.py", line 110, in modules_scan
    cors_main(url,method,headers,body,scanid)
  File "../modules/cors.py", line 69, in cors_main
    origin_headers = generate_origin(url)
  File "../modules/cors.py", line 60, in generate_origin
    postfixurl = domain_name+'.attackersite.com'
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

As I see, in `modules.cors.generate_origin`, from line 59, this caused the error:
```
domain_name = urlparse(url).hostname
postfixurl = domain_name+'.attackersite.com'
```

From the [urlparse's docs](https://docs.python.org/2/library/urlparse.html#urlparse.urlparse), the `hostname` return a `None` object if no hostname is found. 
I think we need to add a validator here to check `domain_name` is not `None`.

**Comment by sagarpo** [comment] 2018-05-04 12:44
@snguyenthanh. What arguments did you pass to astra?

**Comment by snguyenthanh** [comment] 2018-05-04 13:30
@sagarpo I didn't pass anything in the headers and body. I only filled the `Product Name` and `URL`.

**Comment by sagarpo** [comment] 2018-05-06 08:57
@snguyenthanh I am not able to reproduce the same in my system. I have tried the same on my mac and Ubuntu system.  What was the URL did you pass?

**Comment by snguyenthanh** [comment] 2018-05-09 03:51
hmm I also fail to reproduce the error again...
I think just leave this as a note. The issue can be closed.

**Comment by sagarpo** [comment] 2018-05-09 06:30
@snguyenthanh.. cool. I am closing the issue.  Feel free to open it if you face the same.

**Closed by sagarpo** 2018-05-09 06:30 UTC
