### ISSUE TITLE
Unable to run against Postman collection

### ISSUE THREAD

**Issue by dblk4** [flipkart-incubator/Astra#144] opened 2023-06-19 20:42 UTC
I am trying to run Astra with Postman collection but I get the following error message. Is this due to something I may be doing incorrectly?

![image](https://github.com/flipkart-incubator/Astra/assets/98833621/f5c4314f-2964-4546-8da4-770508e4db64)

I am using the Postman toggle and uploading a collection. 
![image](https://github.com/flipkart-incubator/Astra/assets/98833621/7206cf2b-1b67-4103-8aef-76d93b81bb44)

**Comment by tskeel** [comment] 2023-06-22 19:14
I get a similar error, seems to be mongodb related.  

`TypeError: 'Collection' object is not callable. If you meant to call the 'update' method on a 'Collection' object it is failing because no such method exists.
`

**Comment by dblk4** [comment] 2023-07-05 20:03
It would be nice if anyone has a solution to this. I wanted to try out this tool. I did try reinstalling mongo but still nothing.

**Comment by S-Surya** [comment] 2024-05-29 07:36
The issue is not related to postman collection upload. This is solved with #153 . Hence, closing the issue.

**Closed by S-Surya** 2024-05-29 07:36 UTC
